### ISSUE TITLE
How to free the memory allocated?

### ISSUE THREAD

**Issue by suchin** [Riff-js/Riff-js#4]
How to free the memory allocated  using  storage.preference()?

in other word how to delete all the data allocated to key using 'storage.preference()"

**Comment by ckbcorp** [comment]
There is no way to "free" the memory allocation of the storage.preference(). It can only overwrite value.
Depends on the API Manual( http://innovator.samsungmobile.com/onlinedocs/cmsCnts/20100607/0703/0703s.html
), the preference() function has no interface to delete values. 

So, if you want to delete value of the key, you can overwrite null value or "" value for the key value. 
ex: storage.preference( key, "" );
