### ISSUE TITLE
Dynamic creation of image list

### ISSUE THREAD

**Issue by suchin** [Riff-js/Riff-js#5]
Suppose we creating dynamic image list on click event, I found riff css properties are not applied to this, like "rf-state-hand rf-style-thumnail", and ".rf-state-onfocus" classes are not applied to this list item.

So how users need to achieve this?

**Comment by ckbcorp** [comment]
you may achieve it by javascript code such as

$(".someBtn").click(function(){
  $("#listId").find(".rf-style-thumbnail").eq(num).someApis()
})

If this solution is not enough to your problem, please describe your situation( or code, etc.. ) more detail( or you can send email to me.)
