### ISSUE TITLE
Having more then 3 soft button 

### ISSUE THREAD

**Issue by suchin** [Riff-js/Riff-js#8]
Hi,

When we have more then 3 soft buttons in a screen,  buttons wont appear properly at the bottom , contraction happens to the buttons and only 3 buttons will appear.

Please let me know how to resolve this issue??

Thanks,
Suchin

**Comment by Riff-js** [comment]
A number of component changes have been made in the version upgrade.  As part of this upgrade, the "more" functionality has been removed for now.  This feature will return as part of the "Softkey" component update.
